// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnKG5J9Ytde7NlOiT_D49p7RekbbPqxcE',
    appId: '1:201877789698:web:2aa60bee4f397601af1b1b',
    messagingSenderId: '201877789698',
    projectId: 'codename-sc',
    authDomain: 'codename-sc.firebaseapp.com',
    storageBucket: 'codename-sc.appspot.com',
    measurementId: 'G-4FV2RHD12K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdlgjnJVqk9Y2-fFmvQBLZuMrLhYBr_I8',
    appId: '1:201877789698:android:94330e9c9a788c5eaf1b1b',
    messagingSenderId: '201877789698',
    projectId: 'codename-sc',
    storageBucket: 'codename-sc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVzu1cxIBex8NgK23voa2YEmoRxHn8zuU',
    appId: '1:201877789698:ios:5853215b4f07c9c3af1b1b',
    messagingSenderId: '201877789698',
    projectId: 'codename-sc',
    storageBucket: 'codename-sc.appspot.com',
    androidClientId: '201877789698-8t4uu805qqtfaflq2ciiphsnaa4111bk.apps.googleusercontent.com',
    iosClientId: '201877789698-bosjomdn6a9e6guakccthr3ia7mumedp.apps.googleusercontent.com',
    iosBundleId: 'com.dotgeon.sc2023',
  );
}
